CCK = require("CVR.CCK")
UnityEngine = require("UnityEngine")

-- Reference to the animator component (Make sure to bind "animobj" in Unity)
local animator = BoundObjects.animobj:GetComponent("UnityEngine.Animator")

-- Reference to the UI Text component (Bind "NHIEText" in Unity)
local nhieTextObject = BoundObjects.NHIEText

-- Table of NHIE questions (indexed from 1 to 10)
local nhieQuestions = {
    "Testing sync, click the cube",
    "worn two different colored socks without realizing it",
    "pretended to know someone I didn't",
    "accidentally sent a text to the wrong person",
    "sang in the shower",
    "danced in front of a mirror when I thought no one was watching",
    "tripped and fallen in public",
    "gotten lost in a shopping mall",
    "forgotten someone's name right after they told me",
    "eaten food that had fallen on the floor",
    "pretended to be sick to get out of something",
    "walked into a wall",
    "laughed so hard I cried",
    "snorted when laughing",
    "worn mismatched underwear",
    "gotten a wedgie in public",
    "spilled food or drink on myself in public",
    "gotten a brain freeze from eating or drinking something too fast",
    "had a wardrobe malfunction",
    "accidentally liked an old social media post",
    "stalked someone on social media",
    "pretended to be working when I wasn't",
    "called someone the wrong name",
    "forgotten to turn off the microphone during a video call",
    "accidentally pocket dialed someone",
    "worn clothes inside out",
    "gotten food stuck in my teeth and not realized it until later",
    "had a crush on a fictional character",
    "eaten the last piece of food without sharing",
    "blamed a fart on someone else",
    "picked my nose in public",
    "gotten caught singing along to a song",
    "lied about my age",
    "forgotten an important anniversary or birthday",
    "tried on clothes in a store that were too small",
    "walked out of a bathroom with toilet paper stuck to my shoe",
    "gotten caught talking to myself",
    "used the wrong emoji in a text",
    "had a dream that was so weird I couldn't explain it",
    "gotten scared by my own reflection",
    "forgotten where I parked my car",
    "gotten stuck in an elevator",
    "locked myself out of my house",
    "accidentally walked into the wrong bathroom",
    "tried to impress someone and failed miserably",
    "accidentally hit 'reply all' to an email",
    "gotten lost in a corn maze or haunted house",
    "worn the same outfit two days in a row without realizing it",
    "tried a food I thought I would hate but actually liked it",
    "gotten a haircut I immediately regretted",
    "used the wrong name for a pet",
    "tried to fix something myself and made it worse",
    "gotten caught daydreaming in class or at work",
    "worn pajamas in public",
    "tried to sneak food into a movie theater",
    "gotten scared of a spider or insect",
    "gotten caught dancing in my underwear",
    "eaten food that had expired",
    "had a crush on a teacher or boss",
    "gotten caught singing in the car",
    "gotten lost in a virtual reality game",
    "worn a VR headset for so long I forgot where I was",
    "accidentally punched myself in the face while using a VR headset",
    "tripped and fallen while using a VR headset",
    "talked to myself while using a VR headset",
    "gotten scared by a VR horror game",
    "forgotten to eat or drink while using a VR headset",
    "gotten motion sickness from using a VR headset",
    "waved to someone in a VR game who wasn't actually there",
    "tried to high-five someone in a VR game and missed",
    "tried to pet a virtual animal in a VR game",
    "gotten lost in a VR world and couldn't find my way back",
    "had a virtual reality experience that felt too real",
    "forgot to take off my VR headset when I answered the door",
    "gotten so immersed in a VR game that I forgot about the real world",
    "tried to walk through a virtual wall in a VR game",
    "tried to eat virtual food in a VR game",
    "gotten scared by a virtual jump scare in a VR game",
    "laughed out loud at something funny in a VR game",
    "cried at something sad in a VR game",
    "felt a sense of wonder and awe while exploring a VR world",
    "gotten so excited about a VR game that I couldn't sleep",
    "recommended a VR game to a friend",
    "gotten frustrated with a VR game and wanted to quit",
    "felt a sense of accomplishment after completing a VR game",
    "used a VR headset to escape from reality for a while",
    "felt like I was truly present in a VR world",
    "gotten so lost in a VR world that I lost track of time",
    "used a VR headset to explore a place I could never visit in real life",
    "felt like I was part of a community while playing a VR game with others",
    "had a meaningful conversation with someone I met in a VR world",
    "felt like VR had changed my perspective on the world",
    "been amazed by the potential of VR technology",
    "become addicted to VR",
    "eaten something off the floor that wasn't food",
    "accidentally broken something valuable",
    "blamed a mess on my pet",
    "fallen asleep during a meeting or class",
    "pretended to be interested in something I wasn't",
    "eaten food directly from the container",
    "used someone else's toothbrush",
    "snuck into a movie I wasn't old enough to see",
    "forgotten to flush the toilet",
    "sent a message I intended to delete",
    "regifted a present",
    "lied about finishing my homework",
    "gotten caught sneaking snacks into bed",
    "gotten scared of the dark",
    "lied about being busy to avoid plans",
    "eaten the last cookie and then denied it",
    "fallen asleep on public transportation",
    "gotten caught eavesdropping",
    "gotten lost in a book or movie and forgotten about reality",
    "tried to moonwalk and failed",
    "worn a costume in public for no reason",
    "faked an injury to get out of gym class",
    "gotten caught singing in the car with a hairbrush microphone",
    "gotten a sunburn so bad I couldn't wear clothes",
    "accidentally worn my shirt backwards",
    "tried to pass off a store-bought item as homemade",
    "gotten caught taking a selfie in a weird place",
    "gone to the wrong house by mistake",
    "used a fake ID",
    "gotten caught cheating on a test",
    "lied about my skills or experience",
    "forgotten to wear deodorant",
    "gotten caught picking my wedgie",
    "lied about my relationship status",
    "accidentally sent a nude to the wrong person",
    "tried to cut my own hair and messed it up",
    "gotten lost in a foreign country",
    "pretended to like a gift I hated",
    "fallen asleep in a tanning bed",
    "gotten caught sleeping at work or school",
    "lied about my weight",
    "forgotten my anniversary or birthday",
    "accidentally sent an email before it was finished",
    "gotten caught talking to myself out loud",
    "eaten something that fell into the sink",
    "used the same underwear two days in a row",
    "tried to sneak extra toppings on my ice cream",
    "gotten caught picking my nose in traffic",
    "lied about my income",
    "forgotten someone's birthday on Facebook",
    "gotten caught lip-syncing to a song",
    "gotten a speeding ticket",
    "pretended to know how to do something I didn't",
    "eaten something that fell on the ground in a public bathroom",
    "blamed my fart on the dog",
    "gotten caught taking a nap in a public place",
    "used a fake name online",
    "forgotten the lyrics to a song I was singing",
    "eaten food off my shirt",
    "gotten caught looking in someone else's shopping cart",
    "lied about my address",
    "forgotten to brush my teeth",
    "gotten caught taking a picture of someone without their permission",
    "lied about my job",
    "eaten food I dropped in the toilet",
    "blamed a stain on someone else",
    "gotten caught sleeping in class",
    "used a fake phone number",
    "forgotten a friend's name",
    "eaten food off my plate that I dropped on the floor",
    "gotten caught checking myself out in a mirror",
    "lied about my age to get into a club",
    "forgotten where I put my keys",
    "gotten caught sleeping in a movie theater",
    "used a fake name to order food",
    "forgotten someone's name during a conversation",
    "eaten food I found in the couch cushions",
    "gotten caught dancing in the elevator",
    "lied about my qualifications",
    "forgotten where I was going",
    "gotten caught sleeping at a concert",
    "used a fake name to flirt with someone",
    "forgotten my own phone number",
    "eaten food off a stranger's plate",
    "gotten caught dancing in the shower with the water off",
    "lied about being sick to stay home from work",
    "forgotten where I parked my bike",
    "gotten caught sleeping at a party",
    "used a fake name to create a social media account",
    "forgotten how old I am",
    "eaten something I thought was food but wasn't",
    "gotten caught dancing naked in my bedroom",
    "lied about my ethnicity",
    "forgotten my password",
    "gotten caught sleeping on an airplane",
    "used a fake name to enter a contest",
    "forgotten my own name",
    "eaten something that was moldy",
    "gotten caught dancing with a mop as a partner",
    "lied about my sexual orientation",
    "gotten lost in a virtual reality world",
    "worn a VR headset for so long I peed myself",
    "accidentally broken something while playing in VR",
    "tried to eat or drink something while wearing a VR headset",
    "fallen asleep while wearing a VR headset",
    "tried to kiss someone in VR",
    "gotten a nosebleed from playing too much VR",
    "yelled at someone in VR who couldn't hear me",
    "had a VR-induced nightmare",
    "gotten a rash from wearing a VR headset for too long",
    "tried to have a serious conversation with someone in VR",
    "gotten emotionally attached to a VR character",
    "gotten lost in VR and couldn't find my way out",
    "accidentally thrown a controller while playing VR",
    "gotten scared by my own reflection in VR",
    "tried to run in VR and hit a wall",
    "forgotten to take a bathroom break while playing VR",
    "gotten dizzy from spinning around in VR",
    "tried to hug someone in VR and missed",
    "felt a sense of loss when leaving a VR world",
    "gotten so immersed in VR that I forgot to feed my pet",
    "used VR to explore a world that doesn't exist",
    "gotten so excited about VR that I forgot to go to work or school",
    "used VR to learn a new skill",
    "gotten so scared in VR that I screamed out loud",
    "shared a VR experience with someone and made them laugh",
    "felt like VR changed the way I see the world",
    "considered VR to be the future of entertainment"
}

-- Function to update the displayed question based on the animator's int value
function Update()
    -- Get the integer value from the animator's parameter (assuming the parameter is named "NHIECurrentIndex")
    local currentIndex = animator:GetInteger("NHIECurrentIndex")

    -- Safety check to make sure the index is within valid range
    if currentIndex >= 1 and currentIndex <= #nhieQuestions then 
        local textComponent = nhieTextObject:GetComponent("UnityEngine.UI.Text")
        textComponent.text = nhieQuestions[currentIndex]
    else
        print("Error: Invalid index value from animator:", currentIndex) 
    end
end

-- Initial function call to set the text on start
function Start()
    if not nhieTextObject then
        print("Error: NHIEText not bound in ChilloutVR inspector.")
    end
    if not animator then
        print("Error: animobj Animator not found.")
    end
end
